### ISSUE TITLE
Safari, iOS and browser hell

### ISSUE THREAD

**Issue by HarelM** [AyogoHealth/cordova-plugin-oauth#16]
After a short conversation in the Cordova Slack you pointed me to this plugin in order to do OAuth authentication.
I have a few question that I hope you might know the answer for.
I have the following code that currently works for all browsers and for iOS and Android.
I would like to migrate it to use this plugin but I have some doubts:
https://github.com/IsraelHikingMap/Site/blob/1fe490a5bd1f2bd434e5c841ae6889d57e2779eb/IsraelHiking.Web/src/application/services/authorization.service.ts#L62
The following are the pitfalls I fixed in this code:
1. In safari you have to open a window using the click callback without doing anything with `await` so my workaround was to open a window and only after getting all the configuration and token to update the url with them, I'm not sure what to do in case of this plugin...
2. What should I do in case of message callback for regular browsers? Should I only use this plugin in case of a cordova app?
3. Will it conflict with other plugins that are related to app url association (i.e. cordova-plugin-deeplinks)
4. I only use IAB for oauth so I figured I can remove it which is good.

Thanks for all your time contributing to cordova and this plugin! Keep up the good work.

I'm guessing that the bottom line of this issue is that more documentation or examples are needed in order to explain how to use this plugin in all the relevant scenarios (Cordova/non cordova/safari etc)...

**Comment by HarelM** [comment]
@dpogue ? anything?

**Comment by HarelM** [comment]
To answer myself:
1. The plugin is not relevant for the browser and I kept all the browser logic the same.
2. Same as above
3. It conflicts work both in app browser and deep links plugin, I managed to fix the collision by a hack (adding the scheme to deep links configuration and ignoring the event)
4. I was able to remove in-app-browser plugin.

I guess this issue can be closed...

**Comment by gazben** [comment]
@HarelM Same for me, I had to remove the deeplinks and inappbrowser plugins. Can you add more info about your "hack" in point 3? What is you scheme?

**Comment by HarelM** [comment]
The following is the relevant PR I did to close this issue:
https://github.com/IsraelHikingMap/Site/pull/1704/files
I've added the scheme to deeplinks' configuration basically.
Hope that helps.
