### ISSUE TITLE
Plugin crashes when used in Capacitor

### ISSUE THREAD

**Issue by HarelM** [AyogoHealth/cordova-plugin-oauth#29]
Hi,

I'm migrating to capacitor but haven't found a good equivalent to this plugin there.
Unfortunately this plugin crashes in Capacitor environment as can be read in the following bug I opened there:
https://github.com/ionic-team/capacitor/issues/5811

Is there a different way this plugin could send the message without using the webview engine? Maybe some "regular" plugin event that one would register in the js code?
It will be more specific to this plugin, but more readable if one reads the code as it's not a "weird" regular javascript message but rather a plugin callback which is "obvious" that it is part of the plugin API.

If this is something that might interest you, I might be able to send a PR...

**Comment by dpogue** [comment]
It looks like `this.webView.sendJavascript(String js)` might work in this case (and seems to be supported by Capacitor), since we're passing `null` for the callback.

Cordova says it's deprecated because it doesn't properly use a bi-directional bridge, but we're just firing an event so that's probably fine for this use case.

**Comment by HarelM** [comment]
Wow, thanks for the super fast response!
Yes, you are right, this does work although marked as deprecated.
Let me know how you would like to proceed. 
Check for null and fallback to `sendJavasript`? wait to see if ionic's team answers?

This does work in iOS so I believe they have implemented something there that will allow running javascript, so it feels like a missing implementation in android rather than something that is on purpose...

**Comment by dpogue** [comment]
Checking for null and falling back is probably the safest option. Would protect us if Cordova ever decides to drop the deprecated API.

I'm curious to hear what the Capacitor team replies, but it would be nice to be compatible with existing versions of Capacitor.

**Comment by HarelM** [comment]
I've opened a PR for the fix.
From the short test I did it looks like it's working.
