### ISSUE TITLE
Cordova iOS & Cordova Android Min Versions

### ISSUE THREAD

**Issue by ChrisTomAlx** [AyogoHealth/cordova-plugin-oauth#4]
Hey, This seems like a very interesting plugin. I was looking into using it in a project. 
Just have a few doubts. 

1. Is the minimum cordova ios and cordova android versions set in stone? Just wondering because it is using the latest, which sorta puts people using older versions of cordova in a bit of a pickle.
2. There was a note saying there might be conflicts with the inAppBrowser plugin. If possible could you expand on this? As in why would there be a conflict?

Thanks a lot for this plugin
Cheers
Chris

**Comment by dpogue** [comment]
1. Unfortunately, this plugin relies on some API that's only available in cordova-ios >= 5.0.0.

2. This plugin hooks in to `window.open` to intercept windows with `oauth:` in the window name and redirect them to the OAuth flow. This is similar to what older versions of the InApp Browser used to do.

**Comment by ChrisTomAlx** [comment]
Thanks a lot for the helpful reply :) 
Really appreciate it!
