### ISSUE TITLE
iOS 13 changed the ASWebAuthenticationSession API, the plugin stopped working

### ISSUE THREAD

**Issue by mjsarfatti** [AyogoHealth/cordova-plugin-oauth#6]
An app I've released based on this plugin suddenly stopped working right as the authentication process starts, with no error logged whatsoever. I figured out it stopped working for users who updated to iPadOS 13, and then found this resource that seems to be giving an explanation on what happens and how to update the code: https://dev.to/robotsquidward/quick-guide-to-aswebauthenticationsession-api-changes-in-ios-13-4m8i

I know absolutely nothing regarding Swift so I'm not really able to provide a PR unfortunately, but I'd be happy to assist in other ways.

--EDIT--
1. Another plugin which implemented it, but in... Objective-C? I'm really out of my element here https://github.com/jwelker110/cordova-plugin-ios-aswebauthenticationsession-api
2. And this person solved it somehow in a way which I don't even know if it's feasible in Cordova: https://stackoverflow.com/a/58618196/416714

**Comment by dpogue** [comment]
Thanks for bringing this to our attention. Just to check, are you using Xcode 11 to build your app?

I just tested one of our apps on iPadOS 13 and it seemed to be okay, but we're still building with Xcode 10.

**Comment by mjsarfatti** [comment]
Yes, I'm using 11.2

**Comment by dpogue** [comment]
@mjsarfatti I've just published v1.0.1 which has been tested on iOS 13 with Xcode 11 :)

Thanks for bringing this to my attention, and please report any other issues you encounter.
